
// Generated by Cadence Genus(TM) Synthesis Solution 22.11-s104_1
// Generated on: Aug 22 2025 13:34:57 PDT (Aug 22 2025 20:34:57 UTC)

// Verification Directory fv/decoder 

module decoder(A, Z, clk);
  input [3:0] A;
  input clk;
  output [15:0] Z;
  wire [3:0] A;
  wire clk;
  wire [15:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30;
  INVX16 g178(.A (n_27), .Y (Z[4]));
  INVX16 g162(.A (n_30), .Y (Z[14]));
  INVX16 g164(.A (n_14), .Y (Z[1]));
  INVX16 g168(.A (n_9), .Y (Z[6]));
  INVX16 g184(.A (n_7), .Y (Z[10]));
  INVX16 g177(.A (n_29), .Y (Z[3]));
  INVX16 g161(.A (n_26), .Y (Z[8]));
  INVX16 g181(.A (n_13), .Y (Z[11]));
  INVX16 g163(.A (n_28), .Y (Z[9]));
  INVX16 g166(.A (n_19), .Y (Z[7]));
  INVX16 g180(.A (n_10), .Y (Z[0]));
  INVX16 g179(.A (n_22), .Y (Z[2]));
  INVX16 g167(.A (n_11), .Y (Z[13]));
  INVX16 g182(.A (n_16), .Y (Z[5]));
  INVX16 g183(.A (n_8), .Y (Z[12]));
  NAND2X2 g170__2398(.A (n_18), .B (n_24), .Y (n_30));
  NAND2X2 g185__5107(.A (n_17), .B (n_20), .Y (n_29));
  NAND2X2 g171__6260(.A (n_12), .B (n_25), .Y (n_28));
  NAND2X2 g186__4319(.A (n_21), .B (n_15), .Y (n_27));
  NAND2X2 g169__8428(.A (n_25), .B (n_24), .Y (n_26));
  INVX16 g165(.A (n_6), .Y (Z[15]));
  NAND2X2 g187__5526(.A (n_21), .B (n_20), .Y (n_22));
  NAND2X2 g174__6783(.A (n_18), .B (n_17), .Y (n_19));
  NAND2X2 g190__3680(.A (n_17), .B (n_15), .Y (n_16));
  NAND2X2 g172__1617(.A (n_25), .B (n_17), .Y (n_14));
  NAND2X2 g189__2802(.A (n_12), .B (n_20), .Y (n_13));
  NAND2X2 g175__1705(.A (n_12), .B (n_15), .Y (n_11));
  NAND2X2 g188__5122(.A (n_25), .B (n_21), .Y (n_10));
  NAND2X2 g176__8246(.A (n_18), .B (n_21), .Y (n_9));
  NAND2X2 g191__7098(.A (n_15), .B (n_24), .Y (n_8));
  NAND2X2 g192__6131(.A (n_20), .B (n_24), .Y (n_7));
  OR2X2 g173__1881(.A (n_4), .B (n_5), .Y (n_6));
  INVX2 g197(.A (n_5), .Y (n_18));
  CLKAND2X2 g196__5115(.A (A[1]), .B (n_2), .Y (n_20));
  CLKAND2X2 g193__7482(.A (A[2]), .B (n_1), .Y (n_15));
  CLKAND2X2 g194__4733(.A (A[0]), .B (n_3), .Y (n_17));
  INVX2 g198(.A (n_4), .Y (n_12));
  CLKAND2X2 g199__6161(.A (n_3), .B (n_0), .Y (n_21));
  CLKAND2X2 g201__9315(.A (n_2), .B (n_1), .Y (n_25));
  CLKAND2X2 g195__9945(.A (A[3]), .B (n_0), .Y (n_24));
  NAND2X1 g200__2883(.A (A[1]), .B (A[2]), .Y (n_5));
  NAND2X1 g202__2346(.A (A[0]), .B (A[3]), .Y (n_4));
  INVX2 g205(.A (A[2]), .Y (n_2));
  INVX2 g203(.A (A[1]), .Y (n_1));
  INVX2 g204(.A (A[0]), .Y (n_0));
  INVX2 g206(.A (A[3]), .Y (n_3));
endmodule

