use cadence::innovus::PlacementConstraints;
use rivet::{Dag, execute};
use sky130_cadence::{FlatPinInfo, ModuleInfo, sky130_cadence_reference_flow};
use std::path::PathBuf;

fn main() {
    let flow = sky130_cadence_reference_flow(
        PathBuf::from("/home/ff/eecs251b/"),
        PathBuf::from("/scratch/cs199-cbc/rivet/examples/hierarchical/src"),
        Dag {
            node: ModuleInfo {
                module_name: "nbitadder".into(),
                pin_info: FlatPinInfo::None,
                verilog_path: PathBuf::from(
                    "/scratch/cs199-cbc/rivet/examples/hierarchical/src/nbitadder.v",
                ),
                placement_constraints: vec![
                    PlacementConstraints {
                        x: 0.0,
                        y: 0.0,
                        width: 30.0,
                        height: 30.0,
                        left: 0.0,
                        bottom: 0.0,
                        right: 0.0,
                        top: 0.0,
                        constraint_type: "TopLevel".into(),
                        orientation: "r0".into(),
                        top_layer: None,
                        stackup: None,
                        spacing: None,
                        par_blockage_ratio: None,
                        create_physical: false,
                        obs_types: None,
                        obs_layers: None,
                        name: "nbitadder".into(),
                        master: None,
                    },
                    PlacementConstraints {
                        x: 0.0,
                        y: 0.0,
                        width: 30.0,
                        height: 30.0,
                        left: 0.0,
                        bottom: 0.0,
                        right: 0.0,
                        top: 0.0,
                        constraint_type: "Hierarchical".into(),
                        orientation: "r0".into(),
                        top_layer: None,
                        stackup: None,
                        spacing: None,
                        par_blockage_ratio: None,
                        create_physical: false,
                        obs_types: None,
                        obs_layers: None,
                        name: "adder_chain0".into(),
                        master: Some("fulladder".into()),
                    },
                    PlacementConstraints {
                        x: 0.0,
                        y: 0.0,
                        width: 30.0,
                        height: 30.0,
                        left: 0.0,
                        bottom: 0.0,
                        right: 0.0,
                        top: 0.0,
                        constraint_type: "Hierarchical".into(),
                        orientation: "r0".into(),
                        top_layer: None,
                        stackup: None,
                        spacing: None,
                        par_blockage_ratio: None,
                        create_physical: false,
                        obs_types: None,
                        obs_layers: None,
                        name: "adder_chain1".into(),
                        master: Some("nbitadder".into()),
                    },
                    PlacementConstraints {
                        x: 0.0,
                        y: 0.0,
                        width: 30.0,
                        height: 30.0,
                        left: 0.0,
                        bottom: 0.0,
                        right: 0.0,
                        top: 0.0,
                        constraint_type: "Hierarchical".into(),
                        orientation: "r0".into(),
                        top_layer: None,
                        stackup: None,
                        spacing: None,
                        par_blockage_ratio: None,
                        create_physical: false,
                        obs_types: None,
                        obs_layers: None,
                        name: "adder_chain2".into(),
                        master: Some("nbitadder".into()),
                    },
                    PlacementConstraints {
                        x: 0.0,
                        y: 0.0,
                        width: 30.0,
                        height: 30.0,
                        left: 0.0,
                        bottom: 0.0,
                        right: 0.0,
                        top: 0.0,
                        constraint_type: "Hierarchical".into(),
                        orientation: "r0".into(),
                        top_layer: None,
                        stackup: None,
                        spacing: None,
                        par_blockage_ratio: None,
                        create_physical: false,
                        obs_types: None,
                        obs_layers: None,
                        name: "adder_chain3".into(),
                        master: Some("nbitadder".into()),
                    },
                ],
            },
            directed_edges: vec![Dag {
                node: ModuleInfo {
                    module_name: "fulladder".into(),
                    pin_info: FlatPinInfo::None,
                    verilog_path: PathBuf::from(
                        "/scratch/cs199-cbc/rivet/examples/hierarchical/src/fulladder.v",
                    ),
                    placement_constraints: vec![
                        PlacementConstraints {
                            x: 0.0,
                            y: 0.0,
                            width: 30.0,
                            height: 30.0,
                            left: 0.0,
                            bottom: 0.0,
                            right: 0.0,
                            top: 0.0,
                            constraint_type: "TopLevel".into(),
                            orientation: "r0".into(),
                            top_layer: None,
                            stackup: None,
                            spacing: None,
                            par_blockage_ratio: None,
                            create_physical: false,
                            obs_types: None,
                            obs_layers: None,
                            name: "".into(),
                            master: None,
                        },
                        PlacementConstraints {
                            x: 0.0,
                            y: 0.0,
                            width: 30.0,
                            height: 30.0,
                            left: 0.0,
                            bottom: 0.0,
                            right: 0.0,
                            top: 0.0,
                            constraint_type: "Hierarchical".into(),
                            orientation: "r0".into(),
                            top_layer: None,
                            stackup: None,
                            spacing: None,
                            par_blockage_ratio: None,
                            create_physical: false,
                            obs_types: None,
                            obs_layers: None,
                            name: "ha1".into(),
                            master: Some("fulladder".into()),
                        },
                        PlacementConstraints {
                            x: 0.0,
                            y: 0.0,
                            width: 30.0,
                            height: 30.0,
                            left: 0.0,
                            bottom: 0.0,
                            right: 0.0,
                            top: 0.0,
                            constraint_type: "Hierarchical".into(),
                            orientation: "r0".into(),
                            top_layer: None,
                            stackup: None,
                            spacing: None,
                            par_blockage_ratio: None,
                            create_physical: false,
                            obs_types: None,
                            obs_layers: None,
                            name: "ha2".into(),
                            master: Some("fulladder".into()),
                        },
                    ],
                },

                directed_edges: vec![Dag {
                    node: ModuleInfo {
                        module_name: "halfadder".into(),
                        pin_info: FlatPinInfo::None,
                        verilog_path: PathBuf::from(
                            "/scratch/cs199-cbc/rivet/examples/hierarchical/src/halfadder.v",
                        ),

                        placement_constraints: vec![PlacementConstraints {
                            x: 0.0,
                            y: 0.0,
                            width: 30.0,
                            height: 30.0,
                            left: 0.0,
                            bottom: 0.0,
                            right: 0.0,
                            top: 0.0,
                            constraint_type: "TopLevel".into(),
                            orientation: "r0".into(),
                            top_layer: None,
                            stackup: None,
                            spacing: None,
                            par_blockage_ratio: None,
                            create_physical: false,
                            obs_types: None,
                            obs_layers: None,
                            name: "halfadder".into(),
                            master: None,
                        }],
                    },
                    directed_edges: vec![],
                }],
            }],
        },
    );
    // flow.get_mut(&"nbitadder".to_string())
    //     .unwrap()
    //     .par
    //     .add_hook();
    execute(flow.node.par);
}
